### ISSUE TITLE
Help needed regarding authentication

### ISSUE THREAD

**Issue by abhi18av** [ptillemans/smeet-luminus#1]
Hi @ptillemans 

I see that you are also using the `+service` option in luminus template and I am facing some problems trying to authenticate the API wrt the `JWT` backend. 

I am new to clojure and I'd really appreciate if you could please guide me here :)

**Comment by ptillemans** [comment]
I am sorry I just started this repo together with 2 other frameworks to do a 10-minute test and did my prototype in another framework. So I have not advanced further at the moment.

**Comment by abhi18av** [comment]
Hmm, I see. 

Then, I'll close the issue :)
